<a href="https://colab.research.google.com/github/DataMonarch/git-playground/blob/master/GTS555_Python_05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

Asan və sürətli vektor/matriks/tensor əməliyyatları üçün nəzərdə tutulmuş bir python module-u.

![numpy logo.png](https://upload.wikimedia.org/wikipedia/commons/thumb/3/31/NumPy_logo_2020.svg/2560px-NumPy_logo_2020.svg.png)

## Numpy array-lərin yaradılması

Numpy array-ləri PyArrayObject data tipi olaraq saxlanılır. Bu array-lər yaddaşda ardıcıl saxlanıldığı və Numpy library-sinin C proqramlaşdırma dilində yazıldığı üçün onlar üzərində əməllər sadə python list-lərindən çox daha sürətlidir 

In [ ]:
import numpy as np

In [ ]:
x = np.array([1, 2, 3, 4, 5])

In [ ]:
x_list = [1, 2, 3, 4, 5]
x = np.array(x_list)
x

array([1, 2, 3, 4, 5])

In [ ]:
type(x)

numpy.ndarray

Numpy Array-lərlə Python listlər üzərə əməliyyatlar fərqlənir

In [ ]:
print(2 * x)
print(2 * x_list)

[ 2  4  6  8 10]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [ ]:
# list comprehension

y_list = [i**2 for i in range(10)]
y = np.array(y_list)
y.shape

(10,)

In [ ]:
y

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

Aşağıdakı 2 kod blokunu local İDE və ya Jupyter-də yoxlayaraq runtime fərqini daha dəqiq görə bilərsiniz (yuxarıda `y` dəyişəni üçün 1000 element təyin edərək)

In [ ]:
%%time

2 * (y +3)

CPU times: user 44 µs, sys: 0 ns, total: 44 µs
Wall time: 46.7 µs


array([  6,   8,  14,  24,  38,  56,  78, 104, 134, 168])

In [ ]:
%%time


res = []
for y in y_list:
    res.append(2 * (y+3))

res

CPU times: user 4 µs, sys: 1 µs, total: 5 µs
Wall time: 7.15 µs


## Təkölçülü və Çoxölçülü array-lər 

Array-lər n ölçülü (n-dimensional) ola bilər (1 və çox ölçülü)

![](https://i1.wp.com/indianaiproduction.com/wp-content/uploads/2019/06/NumPy-array.png?resize=640%2C307&ssl=1)

* `.shape` - numpy array-in dimension-larını qaytarır
* `.ndim` - numpy array-in dimension-larının sayını qaytarır
* `.size` - numpy array-in bütün axis-lər üzrə elementlərinin sayını qaytarır
* `.flatten()` - n ölçülü numpy array-ini 1 ölçülü array-ə çevirir


In [ ]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int64)
print(x)
print(y)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [ ]:
def shape_dim(np_array):
    print(f"number of dimension of the array --> {np_array.ndim}")
    print(f"shape of the array --> {np_array.shape}")

In [ ]:
shape_dim(x)
shape_dim(y)

number of dimension of the array --> 1
shape of the array --> (5,)
number of dimension of the array --> 2
shape of the array --> (2, 3)


Növbəti 2 kode blokunun nəticələri və məntiqi eyni olduği list comprehension method-u daha sürətlidir

In [ ]:
%%time

z_list = [[[ i+j+k for k in range(5)]
           for j in range(4)]
           for i in range(3)]
z = np.array(z_list)
z

CPU times: user 119 µs, sys: 17 µs, total: 136 µs
Wall time: 143 µs


In [ ]:
%%time

z_list1 = []

for i in range(3):
    for j in range(4):
        for k in range(5):
            z_list1.append(i + k + j)

z1 = np.array(z_list1)
z1

CPU times: user 40 µs, sys: 4 µs, total: 44 µs
Wall time: 48.2 µs


In [ ]:
shape_dim(z)

number of dimension of the array --> 3
shape of the array --> (3, 4, 5)


In [ ]:
print(z.shape)
print(z.size)

(3, 4, 5)
60


In [ ]:
z.dtype

dtype('int64')

Aşağıdakı 2 kod bloku eyni məqsədlidir

In [ ]:
z.size

60

In [ ]:
len(z.flatten())

60

In [ ]:
# class np_array:
#     def __init__(self):

#         self.shape = #array_shape
#         self.size = #array
    
#     def shape(self):
#         #Cython

Numpy arrayin tərkibində fərqli data tipləri olduğu halda bütün elementlər object olaraq *type casting* edilir  

In [ ]:
temp = [["blue", 1, 2],
        ["red", 4, 5]]
temp = np.array(temp)
temp.dtype

dtype('<U21')

## İterativ array yaradılması


* `np.arange()` - numpy array-lərinin yaradılmasında istifadə olunur və funksionallığı python-ın built-in range() funksiyasıyla oxşuyur
* `np.linspace()` - numpy array-lərinin yaradılmasında istifadə olunur və funksionallığı verilmiş aralıqda (aşağıdakı nümunədə 0 və 10 (sonuncu hədd daxil olmamaq şərtilə)) verilmiş sayda (aşağıdakı nümunədə 100) bərabər bölgülü elementli array qaytarır

In [ ]:
x = np.arange(15)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
x = np.array([i for i in range(15)])
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
y = np.linspace(0, 10, 100)
y

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

## Standard Type (filler) array-lərin yaradılması
---


* `np.zeros()` - verilmiş ölçülərdə 1-lərdən ibarət numpy array (ndarray) qaytarır
    * `shape` - tuple şəklində daxil olunmuş ndarray ölçüləri (shape) (aşağıdakı nümunədə (3, 4, 5))
    * `dtype` - yaradılacaq ndarrya-in tərkib elementlərinin data tipi
* `np.ones()` - `np.zeros()` ilə eyni formada işlənir və 1-lərdən ibarət ndarray qaytarır
    * arqumentlər `np.zeros()` ilə eynidir

In [ ]:
np.zeros((3, 4, 5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [ ]:
np.zeros((3, 4, 5), dtype=np.int64)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [ ]:
np.ones((3, 4, 5), dtype=np.int64)

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

## Numpy array-lərinin indekslənməsi
---

1 öıçlülü array-lərdə python list-lərilə eyni formada indekslənmə baş verir. Çox ölçülü array-lərdə isə (ndarray) indekslənmə `arr[i, j, k, ...]` olaraq aparılır (i, j, k slice-lar da ola bilər) və indekslər `[axis0, axis1, axis2,...axis(arr.ndim - 1)]` ardıcıllığında bildirilir

In [ ]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [ ]:
x[3]

3

In [ ]:
x[:3]

array([0, 1, 2])

In [ ]:
x[3:]

array([3, 4])

In [ ]:
x[::-1]

array([4, 3, 2, 1, 0])

In [ ]:
temp = [["blue", 1, 2],
        ["red", 4, 5]]
temp[1][1]

4

In [ ]:
np_temp = np.array(temp)
np_temp[1, 1]

5

In [ ]:
x = np.array([[i for i in range(10, 20)], [i for i in range(100, 110)]])
x

array([[ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109]])

In [ ]:
x[0, 5]

15

In [ ]:
x[1, 2]

102

In [ ]:
x[0, :]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
x[:, 1]

array([ 11, 101])

In [ ]:
x[1, 3:7]

array([103, 104, 105, 106])

In [ ]:
x[1, [1, 3, 5]]

array([101, 103, 105])

## Boolean İndexing
---

Bu üsulla array-in verilmiş bool indekslərinə uyğun olaraq (ancaq True olan xanalar üzrə) uyğun elementlərdən ibarət subset-ini qaytarır. Bunun üçün explicit indexing (lazımi indekslərin True digərlərinin False olaraq bildirilməsilə) və ya complex conditional indexing (mürəkkəb şərti indeksləmə) istifadə olunur. Bir neçə şərt yoxlanıldığı halda **bitwise operator**lardan istifadə olunur. (bu operatorlar barədə faylın sonunda məlumat görə bilərsiniz).

## Array-lərin Yenidən Formalaşdırılması

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
x.reshape((5, 2))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
x = x.reshape((5, 2))
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
x = np.arange(10)
x.reshape((3, 3))

ValueError: ignored

In [ ]:
x = np.arange(9)
x.reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
x.reshape((3, -1))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
y = np.arange(10)
y.reshape((-1, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
np.ones(12).reshape((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.ones(12).reshape((4, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Element üzrə əməliyyatlar

In [ ]:
x = np.arange(10)
y = np.arange(10, 20)[::-1]

In [ ]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
y

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10])

In [ ]:
x + y

array([19, 19, 19, 19, 19, 19, 19, 19, 19, 19])

In [ ]:
x - y

array([-19, -17, -15, -13, -11,  -9,  -7,  -5,  -3,  -1])

In [ ]:
x * y

array([ 0, 18, 34, 48, 60, 70, 78, 84, 88, 90])

In [ ]:
x ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
np.power(y, x)

array([         1,         18,        289,       4096,      50625,
           537824,    4826809,   35831808,  214358881, 1000000000])

## Riyazi funksiyalar metodlar

In [ ]:
x = np.linspace(1, 5, 20)
x

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [ ]:
# 
np.sqrt(x)

array([1.        , 1.10023921, 1.19207912, 1.27733275, 1.35724179,
       1.4327008 , 1.50437957, 1.57279503, 1.63835604, 1.70139262,
       1.76217569, 1.82093094, 1.87784871, 1.93309133, 1.98679854,
       2.03909165, 2.09007681, 2.13984751, 2.18848662, 2.23606798])

In [ ]:
np.log(x)

array([0.        , 0.19105524, 0.35139789, 0.48954823, 0.61090908,
       0.71912267, 0.81676114, 0.90570862, 0.98738665, 1.06289421,
       1.13309846, 1.19869575, 1.26025364, 1.3182409 , 1.37304913,
       1.42500887, 1.47440163, 1.52146914, 1.56642053, 1.60943791])

In [ ]:
np.sin(x)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

## Type casting

In [ ]:
x = np.arange(0, 5, 0.5)
x

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [ ]:
x.astype(np.int64)

array([0, 0, 1, 1, 2, 2, 3, 3, 4, 4])

In [ ]:
x = np.array([1, 2, 3, 4, 5]).astype(float)
x

array([1., 2., 3., 4., 5.])

In [ ]:
x = np.array([-1, 0, 1, 2, 3, 4, 5]).astype(bool)
x

array([ True, False,  True,  True,  True,  True,  True])

In [ ]:
np.array([0, 0, 1, 1]).astype(bool) & np.array([0, 1, 0, 1]).astype(bool)

array([False, False, False,  True])

## Aqqreqat Funksiyaları

In [ ]:
x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# np.min(x)
print(x.min())
# np.max(x)
print(x.max())
# np.mean(x)
print(x.mean())
print(np.median(x))

0
8
4.0
4.0


In [ ]:
print(np.std(x))
print(x.sum())
#print(np.sum(x))

2.581988897471611
36
36


## Axes (koordinat oxları)

In [ ]:
x = np.arange(60).reshape((3, 4, 5))
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [ ]:
x.sum(axis=0)

array([[ 60,  63,  66,  69,  72],
       [ 75,  78,  81,  84,  87],
       [ 90,  93,  96,  99, 102],
       [105, 108, 111, 114, 117]])

In [ ]:
x

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [ ]:
x.sum(axis=1)

array([[ 30,  34,  38,  42,  46],
       [110, 114, 118, 122, 126],
       [190, 194, 198, 202, 206]])

In [ ]:
x.sum(axis=2)

array([[ 10,  35,  60,  85],
       [110, 135, 160, 185],
       [210, 235, 260, 285]])

## Concatenation (birləşdirmə)

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

In [ ]:
np.concatenate([x, y, np.ones(10)])

array([1., 2., 3., 4., 5., 6., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.concatenate([np.zeros((5, 3)), np.ones((5, 3))])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# np.vstack([np.zeros((5, 3)), np.ones((5, 3))])
np.concatenate([np.zeros((5, 3)), np.ones((5, 3))], axis=0)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.vstack([np.zeros((5, 3)), np.ones((5, 3))])

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Array Stacking

In [ ]:
# np.hstack([np.zeros((5, 3)), np.ones((5, 3))])
np.concatenate([np.zeros((5, 3)), np.ones((5, 3))], axis=1)

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [ ]:
np.hstack([np.zeros((5, 3)), np.ones((5, 3))])

array([[0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1.]])

In [ ]:
np.hstack([np.zeros((5, 3)), np.ones((6, 3))])

ValueError: ignored

In [ ]:
np.hstack([np.zeros((5, 3)), np.ones((5, 10))])

array([[0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
z = x

In [ ]:
x[0] = 100
print(x)
print(z)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


In [ ]:
z[1] = -50
print(x)
print(z)

[100 -50   2   3   4   5   6   7   8   9]
[100 -50   2   3   4   5   6   7   8   9]


In [ ]:
y = x.copy()
y[3] = -100
print(y)
print(x)
print(z)

[ 100  -50    2 -100    4    5    6    7    8    9]
[100 -50   2   3   4   5   6   7   8   9]
[100 -50   2   3   4   5   6   7   8   9]


## Percentile (faizli bölgü)
---
Verilmiş array-dən faizli bölgüyə uyğun rəqəmlərin qaytarılması:
* https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

![image.png](https://upload.wikimedia.org/wikipedia/commons/5/5c/PR_and_NCE.gif)

In [ ]:
x = np.random.randint(10, 100, size=20)
x

array([95, 67, 49, 26, 26, 31, 20, 93, 39, 74, 64, 86, 91, 22, 37, 89, 91,
       38, 84, 27])

In [ ]:
np.percentile(x, 10)

25.6

In [ ]:
print(np.percentile(x, 50))
print(x.mean())
print(np.median(x))

56.5
57.45
56.5


In [ ]:
np.percentile(x, 75)

86.75

In [ ]:
print(np.percentile(x, 0))
print(x.min())

20.0
20


In [ ]:
print(np.percentile(x, 100))
print(x.max())

95.0
95


## Matriks Əməlləri
---

Riyazi matriks əməllərinin yerinə yetirilməsi
* `arr.T` - transpose (transpozisiya)
* `@` - 2 matrixi (və ya tensoru) matrix vurulması

In [ ]:
x = np.arange(12).reshape(3, -1)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
x.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [ ]:
y = np.arange(20).reshape(4, -1)
y

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
print(x.shape)
print(y.shape)

(3, 4)
(4, 5)


In [ ]:
x @ y

array([[ 70,  76,  82,  88,  94],
       [190, 212, 234, 256, 278],
       [310, 348, 386, 424, 462]])

In [ ]:
y @ x

ValueError: ignored

In [ ]:
y.T @ x.T

array([[ 70, 190, 310],
       [ 76, 212, 348],
       [ 82, 234, 386],
       [ 88, 256, 424],
       [ 94, 278, 462]])

## Bitwise Operators

Bitwise `&` və `|` operatorlarla `and` və `or` fərqi onların qarşılaşdığı tərəflərə necə yanaşmalarıdır. `and` sadəcə bir növ ətrafındakı şərtlərə "*sən düzgünsənmi?*" deyə bir sual verir (bool `True` olub olmadığına baxmadan) Bu halda yoxlanan ifadə `5 < 7` olarsa bu ifadə özü `True` qaytardığı üçün and bunu `True` olaraq başa düşür. Məsələn, əgər 2 listi yoxlamağa çalışmaq bu halda hər hansısa bir listin sadəcə `True` qaytarması üçün heç bir səbəb yoxdu və listlərin belə bir xüsusiyyəti mövcud deyil. Bu halda python-da `and`in etdiyi listin boş olub olmadğına baxmaqdı. Boş olarsa listi `False`, dolu olduğu halda isə `True` olaraq götürür. Bunun üçün aşağıdakı nümunəyə baxın.


In [ ]:
mylist1 = [True,  True,  True, False,  True]
mylist2 = [False, True, False,  True, False]

In [ ]:
len(mylist1) == len(mylist2)

True

In [ ]:
# bu kod Python məntiqinə uyğun deyil və istifadə olunmamalıdır
# Dərindən öyrənmək üçün nəticəyə baxaq
mylist1 and mylist2

[False, True, False, True, False]

Burada Python bir bir hər 2 listin elementlərini müqayisə etmir. Bunu etdiyi halda nəticə aşağıdakı kimi olmalı olardı:

```
[False, True, Flase, False, False]
```

Burada baş verən isə odur ki, ilk öncə Python 1ci listin boş olmadığını görərək ona `True` deyir sonra isə əvvəl 2 listi müqayisə edə bilmədiyi halda artıq bool `True`nu 2ci listin elementlərinə nisbətən müqayisə edə bildiyi üçün 2ci list elementlərinin hər birini `True`-la qarşılaşdırır.

Bu operatorlar isə verilmiş tərəflərin binary (2li sistemdə) olan yazılışlarını müqayisə edir və hər bir object (listlər, numpy arraylər, dictionary-lər, setlər və s.) bu operatordan öz məqsədlərinə uyğun olaraq fərqli üsulda istifadə edir. Məsələn sadə olaraq 2 integer-i müqayisə etsək:

In [ ]:
x = 4
y = 9
print(bin(x))
print(bin(y))

0b100
0b1001


In [ ]:
print(x & y)
print(x | y)

0
13


In [ ]:
print(bin(x & y))
print(bin(x | y))

0b0
0b1101


In [ ]:
x = 12
y = 9
print(bin(x))
print(bin(y))

0b1100
0b1001


In [ ]:
print(x & y)
print(x | y)

8
13


In [ ]:
print(bin(x & y))
print(bin(x | y))

0b1000
0b1101


Burada 2 toxunmalı olduğumuz məqam var:
1. 2li yazılışdakı rəqəmlər müqayisə olunur yəni 1000 və 1101 arasındakı müayisədən 1000 alınır (`1 and 0` əməliyyatının nəticəsi kimi)
2. fərqli uzunluqda olan 2li yazılışlar müqayisə olunmur və 0 qaytarılır

In [ ]:
# Bu əməli python listi başa düşmür

mylist1 & mylist2

TypeError: ignored

In [ ]:
# burada numpy array-lərin boş və ya dolu olmasına görə 
# müayisə etmədiyi üçün əməliyyatı yerinə yetirə bilmir

np.array(mylist1) and np.array(mylist2)

ValueError: ignored

In [ ]:
# burada isə numpy sadəcə olaraq array-lərin elementlərini bir bir müqayisə edir 
# Artqı buradakı müqayisə `==` operatoru üzrə gedir 
# arr1[0] == arr2[0]? 

np.array(mylist1) & np.array(mylist2)

array([False,  True, False, False, False])

In [ ]:
x = np.arange(10, 15)
x

array([10, 11, 12, 13, 14])

In [ ]:
x[[True, False, True, True, False]]

array([10, 12, 13])

In [ ]:
y = np.arange(10, 30)
y

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [ ]:
y < 20

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False, False, False,
       False, False])

In [ ]:
y[y < 20]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
y[(y < 20) & (y % 2 == 0)]

array([10, 12, 14, 16, 18])

In [ ]:
print(y[(y < 20) & (y % 2 == 0)])

[10 12 14 16 18]


In [ ]:
print(y[(y < 20) | (y > 25)])

[10 11 12 13 14 15 16 17 18 19 26 27 28 29]


In [ ]:
y[~(y < 20)]

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [ ]:
idx = np.arange(10, 20, 2)
arr = np.linspace(0, 100, 100)
arr

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

In [ ]:
print(idx)
arr[idx]

[10 12 14 16 18]


array([10.1010101 , 12.12121212, 14.14141414, 16.16161616, 18.18181818])

In [ ]:
import matplotlib.pyplot as plt